In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
%matplotlib inline



In [ ]:
data17 = pd.read_csv("2017.csv")

In [ ]:
data18 = pd.read_csv("2018.csv")

In [ ]:
combine_data = pd.concat([data17, data18])

In [ ]:
combine_data['flat'].describe()

count     189742
unique      3379
top            1
freq       13630
Name: flat, dtype: object

In [ ]:
combine_data['floor_level'].describe()

count     197545
unique        26
top          1st
freq       63262
Name: floor_level, dtype: object

In [ ]:
combine_data['latitude'].describe()

count    1.888177e+06
mean     5.235284e+01
std      1.144130e+00
min      4.991321e+01
25%      5.145793e+01
50%      5.219065e+01
75%      5.337324e+01
max      5.579742e+01
Name: latitude, dtype: float64

In [ ]:
combine_data['longitude'].describe()

count    1.888177e+06
mean    -1.365917e+00
std      1.327566e+00
min     -6.352647e+00
25%     -2.247356e+00
50%     -1.402552e+00
75%     -2.731810e-01
max      1.758397e+00
Name: longitude, dtype: float64

In [ ]:
combine_data['number_of_rooms'].describe()

count    850133.000000
mean          4.564547
std           1.730543
min           1.000000
25%           3.000000
50%           4.000000
75%           5.000000
max          91.000000
Name: number_of_rooms, dtype: float64

In [ ]:
combine_data['old_new'].describe()

count     1978777
unique          2
top             N
freq      1768260
Name: old_new, dtype: object

In [ ]:
combine_data['postcode'].describe()

count      1978777
unique      767762
top       YO10 3FT
freq           493
Name: postcode, dtype: object

In [ ]:
combine_data['postcode_sector'].describe()

count     1978777
unique       8340
top         E16 2
freq         1659
Name: postcode_sector, dtype: object

In [ ]:
combine_data['ppd_category'].describe()

count     1978777
unique          2
top             A
freq      1701330
Name: ppd_category, dtype: object

In [ ]:
combine_data['property_type'].describe()

count     1978777
unique          5
top             T
freq       541990
Name: property_type, dtype: object

In [ ]:
combine_data['street'].describe()

count         1978776
unique         232912
top       HIGH STREET
freq            15531
Name: street, dtype: object

In [ ]:
combine_data['total_floor_area'].describe()

count    960356.000000
mean         90.015271
std          52.947399
min           0.000000
25%          64.000000
50%          81.000000
75%         104.000000
max        5327.890000
Name: total_floor_area, dtype: float64

In [ ]:
print(combine_data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1978777 entries, 0 to 986564
Data columns (total 43 columns):
 #   Column                          Dtype  
---  ------                          -----  
 0   transaction_id                  object 
 1   created                         object 
 2   duration                        object 
 3   price                           int64  
 4   old_new                         object 
 5   ppd_category                    object 
 6   property_type                   object 
 7   flat                            object 
 8   floor_level                     object 
 9   number_of_rooms                 float64
 10  total_floor_area                float64
 11  epc_current_energy_rating       object 
 12  epc_potential_energy_rating     object 
 13  epc_property_type               object 
 14  epc_built_form                  object 
 15  epc_energy_consumption_current  float64
 16  epc_lighting_cost_current       float64
 17  epc_heating_cost_current    

In [ ]:
print(combine_data['flat'].isnull().sum())

1789035


In [ ]:
print(combine_data['floor_level'].isnull().sum())

1781232


In [ ]:
print(combine_data['latitude'].isnull().sum())

90600


In [ ]:
print(combine_data['longitude'].isnull().sum())

90600


In [ ]:
print(combine_data['number_of_rooms'].isnull().sum())

1128644


In [ ]:
print(combine_data['old_new'].isnull().sum())

0


In [ ]:
print(combine_data['postcode'].isnull().sum())

0


In [ ]:
print(combine_data['postcode_sector'].isnull().sum())

0


In [ ]:
print(combine_data['ppd_category'].isnull().sum())

0


In [ ]:
print(combine_data['property_type'].isnull().sum())

0


In [ ]:
print(combine_data['street'].isnull().sum())

1


In [ ]:
print(combine_data['total_floor_area'].isnull().sum())

1018421


In [ ]:
df.flat.unique()

NameError: name 'df' is not defined

In [ ]:
combine_data.flat.unique()

array([nan, 'P M 509', 'P M 109', ..., 'COTTAGE 3', '4400', '64A'],
      dtype=object)

In [ ]:
combine_data.floor_level.unique()

array([nan, '1st', 'ground floor', '3rd', 'Ground', '5th', '2nd',
       'mid floor', 'top floor', '6th', '4th', 'Basement', '20th', '10th',
       '7th', '15th', '8th', '9th', '12th', '11th', '17th', '14th',
       '13th', '18th', '16th', '21st or above', '19th'], dtype=object)

In [ ]:
combine_data.latitude.unique()

array([53.177751, 51.380891, 52.469943, ..., 51.791576, 50.664687,
       51.315924])

In [ ]:
combine_data.longitude.unique()

array([-1.191828, -1.605473, -2.134401, ..., -0.278515, -1.271613,
       -0.279389])

In [ ]:
combine_data.number_of_rooms.unique()

array([nan,  9.,  6.,  5.,  4.,  3.,  7., 10.,  2.,  8., 11.,  1., 22.,
       13., 12., 14., 15., 18., 20., 25., 54., 17., 83., 45., 23., 16.,
       55., 19., 71., 48., 26., 40., 32., 41., 50., 21., 77., 34., 78.,
       33., 51., 28., 39., 30., 35., 82., 42., 85., 90., 60., 27., 57.,
       44., 80., 43., 59., 66., 91., 37., 86., 29., 47., 79., 88., 24.,
       75.])

In [ ]:
combine_data.old_new.unique()

array(['Y', 'N'], dtype=object)

In [ ]:
combine_data.postcode.unique()

array(['NG19 8RX', 'SN8 3LP', 'DY5 3XJ', ..., 'AL4 9BQ', 'PO30 3BP',
       'KT18 7EH'], dtype=object)

In [ ]:
combine_data.postcode_sector.unique()

array(['NG19 8', 'SN8 3', 'DY5 3', ..., 'SO57 7', 'CB2 6', 'EC2R 8'],
      dtype=object)

In [ ]:
combine_data.ppd_category.unique()

array(['B', 'A'], dtype=object)

In [ ]:
combine_data.property_type.unique()

array(['T', 'D', 'S', 'F', 'O'], dtype=object)

In [ ]:
combine_data.street.unique()

array(['PICCADILLY CLOSE', 'FOREST HILL', 'PATTERDALE WAY', ...,
       'STANES ROAD', 'TOWER HILL LANE', 'BIRCHMORE LANE'], dtype=object)

In [ ]:
combine_data.total_floor_area.unique()

array([    nan, 173.04 , 105.   , ..., 309.25 , 113.622,  54.296])

In [ ]:
combine_data['address_id'].describe()

count    1.978777e+06
mean     9.855989e+07
std      5.385521e+06
min      8.857593e+07
25%      9.381703e+07
50%      9.918091e+07
75%      1.036150e+08
max      1.056136e+08
Name: address_id, dtype: float64

In [ ]:
print(combine_data['address_id'].isnull().sum())

0


In [ ]:
combine_data.address_id.unique()

array([102877980,  97804281, 101429204, ...,  91529444,  98714471,
       101977493], dtype=int64)

In [ ]:
combine_data['building_name'].describe()

count     296276
unique     91522
top         UNIT
freq        4568
Name: building_name, dtype: object

In [ ]:
print(combine_data['building_name'].isnull().sum())

1682501


In [ ]:
combine_data.building_name.unique()

array([nan, 'BRIDGE HOUSE', 'PACKHAM COURT', ..., 'SUNNINGDALE GARDENS',
       'SOUTHVIEW BUSINESS PARK', 'PEN-Y-BONT YARD'], dtype=object)

In [ ]:
combine_data['building_number'].describe()

count     1792911
unique       7893
top             1
freq        64478
Name: building_number, dtype: object

In [ ]:
print(combine_data['building_number'].isnull().sum())

185866


In [ ]:
combine_data.building_number.unique()

array(['24', '3', '36', ..., '452G', '33F', '219-221'], dtype=object)

In [ ]:
combine_data['city'].describe()

count        1978743
unique           350
top       BIRMINGHAM
freq           29598
Name: city, dtype: object

In [ ]:
print(combine_data['city'].isnull().sum())

34


In [ ]:
combine_data.city.unique()

array(['MANSFIELD', 'WILTSHIRE', 'DUDLEY', 'SOLIHULL', 'BLABY', 'DOVER',
       'CAERPHILLY', 'WORTHING', 'MANCHESTER', 'CHELMSFORD', 'LEEDS',
       'NOTTINGHAM', 'ARUN', 'EPSOM-AND-EWELL', 'SEVENOAKS',
       'STRATFORD-ON-AVON', 'HEREFORDSHIRE-COUNTY-OF', 'BABERGH',
       'KINGSTON-UPON-HULL-CITY-OF', 'TORBAY', 'STOCKPORT', 'BOLTON',
       'COUNTY-DURHAM', 'EPPING-FOREST', 'BATH-AND-NORTH-EAST-SOMERSET',
       'NORTH-LINCOLNSHIRE', 'NEWCASTLE-UNDER-LYME', 'CASTLE-POINT',
       'BARKING-AND-DAGENHAM', 'NORWICH', 'CORNWALL', 'HARINGEY',
       'DACORUM', 'EAST-HAMPSHIRE', 'WEST-LINDSEY', 'SEFTON', 'RUSHMOOR',
       'WALSALL', 'SCARBOROUGH', 'BOURNEMOUTH', 'BOSTON', 'TEST-VALLEY',
       'HAVERING', 'RUNNYMEDE', 'KIRKLEES', 'CONWY', 'WARRINGTON',
       'CARDIFF', 'WEST-LANCASHIRE', 'LAMBETH', 'HORSHAM', 'POWYS',
       'WIGAN', 'BIRMINGHAM', 'STOCKTON-ON-TEES', 'CHELTENHAM', 'DERBY',
       'SANDWELL', 'LEICESTER', 'GWYNEDD', 'ROTHERHAM', 'BRIDGEND',
       'PETERBOROUGH', 'WESTM

In [ ]:
combine_data['closestpark'].describe()

count    1.746376e+06
mean     9.640953e+02
std      7.925460e+02
min      3.000000e+00
25%      4.120000e+02
50%      7.120000e+02
75%      1.241000e+03
max      4.838000e+03
Name: closestpark, dtype: float64

In [ ]:
print(combine_data['closestpark'].isnull().sum())

232401


In [ ]:
combine_data.closestpark.unique()

array([ 674.,   nan,  745., ..., 4697., 4615., 4672.])

In [ ]:
combine_data['closestschool'].describe()

count    1.787248e+06
mean     4.835813e+02
std      4.318005e+02
min      0.000000e+00
25%      2.420000e+02
50%      3.820000e+02
75%      5.740000e+02
max      4.743000e+03
Name: closestschool, dtype: float64

In [ ]:
print(combine_data['closestschool'].isnull().sum())

191529


In [ ]:
combine_data.closestpark.unique()

array([ 674.,   nan,  745., ..., 4697., 4615., 4672.])

In [ ]:
combine_data['closeststop'].describe()

count    1.866905e+06
mean     3.112370e+02
std      4.756355e+02
min      5.321700e-01
25%      9.674732e+01
50%      1.605978e+02
75%      2.938576e+02
max      4.815169e+03
Name: closeststop, dtype: float64

In [ ]:
print(combine_data['closeststop'].isnull().sum())

111872


In [ ]:
combine_data.closeststop.unique()

array([ 130.41936945,  446.80579482,  310.74340407, ..., 1549.24298799,
        799.37498681,   33.97629236])

In [ ]:
combine_data['created'].describe()

count        1978777
unique           728
top       2017-06-30
freq           19604
Name: created, dtype: object

In [ ]:
print(combine_data['created'].isnull().sum())

0


In [ ]:
combine_data.created.unique()

array(['2017-06-22', '2017-10-13', '2017-03-08', '2017-10-27',
       '2017-05-05', '2017-05-24', '2017-12-15', '2017-10-06',
       '2017-04-28', '2017-05-12', '2017-03-31', '2017-10-05',
       '2017-01-09', '2017-10-19', '2017-06-30', '2017-12-08',
       '2017-03-24', '2017-10-25', '2017-02-06', '2017-09-12',
       '2017-02-17', '2017-02-28', '2017-11-30', '2017-03-30',
       '2017-11-01', '2017-07-26', '2017-11-24', '2017-09-21',
       '2017-10-15', '2017-05-15', '2017-11-10', '2017-03-03',
       '2017-11-17', '2017-12-14', '2017-02-14', '2017-08-21',
       '2017-08-25', '2017-03-10', '2017-02-24', '2017-04-19',
       '2017-06-23', '2017-07-04', '2017-10-12', '2017-07-28',
       '2017-05-19', '2017-07-07', '2017-03-17', '2017-09-22',
       '2017-07-11', '2017-03-20', '2017-04-07', '2017-09-13',
       '2017-01-06', '2017-09-29', '2017-12-13', '2017-08-15',
       '2017-08-17', '2017-01-16', '2017-02-03', '2017-05-02',
       '2017-04-06', '2017-04-12', '2017-04-13', '2017-

In [ ]:
combine_data['crimesin3km_antisocial'].describe()

count    1.887698e+06
mean     2.356189e+03
std      2.905756e+03
min      0.000000e+00
25%      4.490000e+02
50%      1.433000e+03
75%      3.040000e+03
max      2.307400e+04
Name: crimesin3km_antisocial, dtype: float64

In [ ]:
print(combine_data['crimesin3km_antisocial'].isnull().sum())

91079


In [ ]:
combine_data.crimesin3km_antisocial.unique()

array([7.4100e+02, 1.0000e+01, 1.5760e+03, ..., 1.5488e+04, 1.3462e+04,
       1.6974e+04])

In [ ]:
combine_data['distance_center'].describe()

count    1.888177e+06
mean     6.190759e+00
std      7.257374e+00
min      3.301802e-03
25%      1.796913e+00
50%      3.754652e+00
75%      7.704068e+00
max      8.374496e+01
Name: distance_center, dtype: float64

In [ ]:
print(combine_data['distance_center'].isnull().sum())

90600


In [ ]:
combine_data.distance_center.unique()

array([ 3.65830015, 27.20535195,  5.65961217, ...,  5.95727623,
        4.2135803 ,  2.08642182])

In [ ]:
combine_data['duration'].describe()

count     1978777
unique          2
top             F
freq      1502069
Name: duration, dtype: object

In [ ]:
print(combine_data['duration'].isnull().sum())

0


In [ ]:
combine_data.distance_center.unique()

array([ 3.65830015, 27.20535195,  5.65961217, ...,  5.95727623,
        4.2135803 ,  2.08642182])

In [ ]:
combine_data['epc_built_form'].describe()

count            913385
unique                6
top       Semi-Detached
freq             283499
Name: epc_built_form, dtype: object

In [ ]:
print(combine_data['epc_built_form'].isnull().sum())

1065392


In [ ]:
combine_data.epc_built_form.unique()

array([nan, 'Detached', 'End-Terrace', 'Mid-Terrace', 'Semi-Detached',
       'Enclosed Mid-Terrace', 'Enclosed End-Terrace'], dtype=object)

In [ ]:
combine_data['epc_current_energy_rating'].describe()

count     960356
unique         8
top            D
freq      392862
Name: epc_current_energy_rating, dtype: object

In [ ]:
print(combine_data['epc_current_energy_rating'].isnull().sum())

1018421


In [ ]:
combine_data.epc_built_form.unique()

array([nan, 'Detached', 'End-Terrace', 'Mid-Terrace', 'Semi-Detached',
       'Enclosed Mid-Terrace', 'Enclosed End-Terrace'], dtype=object)

In [ ]:
combine_data['epc_energy_consumption_current'].describe()

count    960356.000000
mean        982.718065
std        4775.125172
min       -1323.000000
25%         196.000000
50%         262.000000
75%         349.000000
max      416354.000000
Name: epc_energy_consumption_current, dtype: float64

In [ ]:
print(combine_data['epc_energy_consumption_current'].isnull().sum())

1018421


In [ ]:
combine_data.epc_energy_consumption_current.unique()

array([   nan,   297.,    95., ...,  9214., 25630., 21185.])

In [ ]:
combine_data['epc_flat_storey_count'].describe()

count    85957.000000
mean         3.168922
std          2.482652
min          0.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         63.000000
Name: epc_flat_storey_count, dtype: float64

In [ ]:
print(combine_data['epc_flat_storey_count'].isnull().sum())

1892820


In [ ]:
combine_data.epc_flat_storey_count.unique()

array([nan,  3.,  4.,  2.,  6.,  5.,  1.,  7.,  0., 11.,  8., 13.,  9.,
       10., 12., 14., 16., 17., 15., 20., 19., 18., 23., 24., 30., 21.,
       41., 39., 26., 25., 48., 45., 47., 38., 28., 29., 27., 22., 31.,
       33., 34., 55., 44., 49., 61., 37., 63.])

In [ ]:
combine_data['epc_floor_height'].describe()

count    525532.000000
mean          2.453044
std           0.605628
min           0.000000
25%           2.330000
50%           2.400000
75%           2.510000
max         230.000000
Name: epc_floor_height, dtype: float64

In [ ]:
print(combine_data['epc_floor_height'].isnull().sum())

1453245


In [ ]:
combine_data.epc_floor_height.unique()

array([  nan, 2.7  , 2.3  , ..., 3.589, 4.72 , 2.951])

In [ ]:
combine_data['epc_glazed_area'].describe()

count     850134
unique         5
top       Normal
freq      823169
Name: epc_glazed_area, dtype: object

In [ ]:
print(combine_data['epc_glazed_area'].isnull().sum())

1128643


In [ ]:
combine_data.epc_glazed_area.unique()

array([nan, 'Normal', 'Less Than Typical', 'Much More Than Typical',
       'More Than Typical', 'Much Less Than Typical'], dtype=object)

In [ ]:
combine_data['epc_heating_cost_current'].describe()

count    960356.000000
mean        701.405613
std         540.060623
min        -801.000000
25%         394.000000
50%         594.000000
75%         852.000000
max       62707.000000
Name: epc_heating_cost_current, dtype: float64

In [ ]:
print(combine_data['epc_heating_cost_current'].isnull().sum())

1018421


In [ ]:
combine_data.epc_heating_cost_current.unique()

array([       nan, 1489.     ,  320.     , ...,  783.87616,  376.97662,
        642.2242 ])

In [ ]:
combine_data['epc_hot_water_cost_current'].describe()

count    960356.000000
mean        140.895424
std          75.444502
min         -31.000000
25%          95.000000
50%         116.000000
75%         161.000000
max        1411.000000
Name: epc_hot_water_cost_current, dtype: float64

In [ ]:
print(combine_data['epc_hot_water_cost_current'].isnull().sum())

1018421


In [ ]:
combine_data.epc_hot_water_cost_current.unique()

array([      nan, 259.     ,  87.     , ...,  98.16898, 199.71954,
        84.10469])

In [ ]:
combine_data['epc_lighting_cost_current'].describe()

count    960356.000000
mean         78.930790
std          40.838095
min          -8.000000
25%          54.000000
50%          72.000000
75%          95.000000
max        6760.000000
Name: epc_lighting_cost_current, dtype: float64

In [ ]:
print(combine_data['epc_lighting_cost_current'].isnull().sum())

1018421


In [ ]:
combine_data.epc_lighting_cost_current.unique()

array([       nan, 189.      ,  67.      , ...,  71.114075,  48.40139 ,
        56.10401 ])

In [ ]:
combine_data['epc_number_open_fireplaces'].describe()

count    853001.000000
mean          0.200909
std           0.572482
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          75.000000
Name: epc_number_open_fireplaces, dtype: float64

In [ ]:
print(combine_data['epc_number_open_fireplaces'].isnull().sum())

1125776


In [ ]:
combine_data.epc_number_open_fireplaces.unique()

array([nan,  0.,  1.,  2.,  3.,  4.,  6.,  7.,  5.,  9., 10.,  8., 12.,
       18., 11., 15., 30., 20., 14., 50., 21., 19., 25., 16., 75., 60.,
       40.])

In [ ]:
combine_data['epc_potential_energy_rating'].describe()

count     960356
unique         8
top            C
freq      378269
Name: epc_potential_energy_rating, dtype: object

In [ ]:
print(combine_data['epc_potential_energy_rating'].isnull().sum())

1018421


In [ ]:
combine_data.epc_potential_energy_rating.unique()

array([nan, 'D', 'A', 'C', 'B', 'E', 'F', 'G', 'I'], dtype=object)

In [ ]:
combine_data['epc_property_type'].describe()

count     960356
unique         5
top        House
freq      689814
Name: epc_property_type, dtype: object

In [ ]:
print(combine_data['epc_property_type'].isnull().sum())

1018421


In [ ]:
combine_data.epc_property_type.unique()

array([nan, 'House', 'Flat', 'Maisonette', 'Bungalow', 'Park home'],
      dtype=object)

In [ ]:
combine_data['epc_roof_description'].describe()

count                              959962
unique                                855
top       Pitched, 100 mm loft insulation
freq                               122497
Name: epc_roof_description, dtype: object

In [ ]:
print(combine_data['epc_roof_description'].isnull().sum())

1018815


In [ ]:
combine_data.epc_roof_description.unique()

array([nan, 'Pitched, insulated (assumed)',
       'Average thermal transmittance 0.14 W/m²K', 'Roof',
       'Pitched, 200 mm loft insulation',
       'Pitched, 150 mm loft insulation', '(another dwelling above)',
       'Roof room(s), ceiling insulated',
       'Pitched, 100 mm loft insulation', 'Flat, insulated (assumed)',
       'Pitched, 150mm loft insulation', 'Pitched, insulated at rafters',
       'Pitched, 50mm loft insulation', 'Pitched, no insulation',
       'Pitched, 250 mm loft insulation',
       'Pitched, no insulation (assumed)',
       'Pitched, 270 mm loft insulation',
       'Pitched, 75 mm loft insulation', 'Pitched, 0 mm loft insulation',
       'Pitched, limited insulation (assumed)',
       'Pitched, 50 mm loft insulation',
       'Pitched, 300+ mm loft insulation', '(other premises above)',
       'Pitched, loft insulation', 'Roof room(s), insulated (assumed)',
       'Pitched, 300 mm loft insulation',
       'Average thermal transmittance 0.11 W/m?K',
       '

In [ ]:
combine_data['epc_roof_energy_eff'].describe()

count     836781
unique         5
top         Good
freq      358283
Name: epc_roof_energy_eff, dtype: object

In [ ]:
print(combine_data['epc_roof_energy_eff'].isnull().sum())

1141996


In [ ]:
combine_data.epc_roof_energy_eff.unique()

array([nan, 'Average', 'Very Good', 'Good', 'Poor', 'Very Poor'],
      dtype=object)

In [ ]:
combine_data['epc_walls_description'].describe()

count                                             960301
unique                                              1067
top       Solid brick, as built, no insulation (assumed)
freq                                              193323
Name: epc_walls_description, dtype: object

In [ ]:
print(combine_data['epc_walls_description'].isnull().sum())

1018476


In [ ]:
combine_data.epc_walls_description.unique()

array([nan, 'Cavity wall, as built, insulated (assumed)',
       'Average thermal transmittance 0.24 W/m²K', ...,
       'Average thermal transmittance 0.17 W/m2K',
       'Average thermal transmittance 1.35 W/mA?K',
       'Average thermal transmittance 0.21 W/m?K|Trawsyriannedd thermol cyfartalog 0.21 W/m?K'],
      dtype=object)

In [ ]:
combine_data['epc_walls_energy_eff'].describe()

count     947395
unique         5
top         Good
freq      432153
Name: epc_walls_energy_eff, dtype: object

In [ ]:
print(combine_data['epc_walls_energy_eff'].isnull().sum())

1031382


In [ ]:
combine_data.epc_walls_energy_eff.unique()

array([nan, 'Good', 'Very Good', 'Very Poor', 'Poor', 'Average'],
      dtype=object)

In [ ]:
combine_data['epc_windows_description'].describe()

count                  960348
unique                     52
top       Fully double glazed
freq                   704779
Name: epc_windows_description, dtype: object

In [ ]:
print(combine_data['epc_windows_description'].isnull().sum())

1018429


In [ ]:
combine_data.epc_windows_description.unique()

array([nan, 'Partial double glazing', 'High performance glazing',
       'Window', 'Fully double glazed', 'Mostly secondary glazing',
       'Single glazed', 'Partial secondary glazing',
       'Mostly double glazing', 'Multiple glazing throughout',
       'Some double glazing', 'Full secondary glazing', 'SAP05:Windows',
       'Fully triple glazed', 'Partial multiple glazing',
       'Gwydrau dwbl llawn', 'Single glazeddouble glazing',
       'Some secondary glazing', 'Fully secondary glazing',
       'Mostly multiple glazing', 'Single glazedsecondary glazing',
       'Fully secondary glazed', 'Secondary glazing',
       'Mostly  double glazing', 'Some  double glazing',
       'Some multiple glazing', 'Partial triple glazing',
       'Full triple glazing', 'double glazing',
       'High performance glazing|Ffenestri perfformiad uchel',
       'Fully double glazed|Gwydrau dwbl llawn', 'Mostly triple glazing',
       'Multiple glazing throughout|Gwydrau lluosog ym mhobman',
       'Mult

In [ ]:
combine_data['epc_windows_energy_eff'].describe()

count      952546
unique          5
top       Average
freq       486525
Name: epc_windows_energy_eff, dtype: object

In [ ]:
print(combine_data['epc_windows_energy_eff'].isnull().sum())

1026231


In [ ]:
combine_data.epc_windows_energy_eff.unique()

array([nan, 'Average', 'Very Good', 'Good', 'Poor', 'Very Poor'],
      dtype=object)